#!/bin/bash

LOG_FILE1=test_3_3.log
LOG_FILE2=test_5_5.log
#mvn clean install
touch $LOG_FILE1
touch $LOG_FILE2

(echo 1
echo John 
echo Sara
echo 1 1 3 5 1 2 9 8 1 5 2 9 7 4 6 3 8 9 5 3 4 7 6) | java -jar target/OX-2.0-jar-with-dependencies.jar | tee ${LOG_FILE1}

(echo 2 
echo Staś
echo Grażyna 
echo 2 2 5 7 8 1 24 13 21 19 22 25 7 13 8 9 25 1 11 22 5 6 18 16 2 21 20 10 12 4 3 19 14 13 2 17 1 21 3 9 4 5) | java -jar target/OX-2.0-jar-with-dependencies.jar | tee ${LOG_FILE2}
